language: java
sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y tesseract-ocr ghostscript
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V
script: mvn test -Dgpg.skip=true
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8



